apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nestjs-car-rental.fullname" . }}
  labels:
    {{- include "nestjs-car-rental.labels" . | nindent 4 }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name | quote }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nestjs-car-rental.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nestjs-car-rental.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        envFrom:
        - secretRef:
            name: {{ include "nestjs-car-rental.fullname" . }}-secrets
        volumeMounts:
        - name: service-account
          mountPath: /usr/src/app/service-account.json
          subPath: service-account.json
      volumes:
      - name: service-account
        secret:
          secretName: {{ include "nestjs-car-rental.fullname" . }}-secrets
          items:
          - key: service-account.json
            path: service-account.json