apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nestjs-car-rental.fullname" . }}-secrets
  labels:
    {{- include "nestjs-car-rental.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  SERVICE_ACCOUNT_KEY_PATH: {{ .Values.secrets.serviceAccountKeyPath | b64enc | quote }}
  STORAGE_BUCKET_NAME: {{ .Values.secrets.storageBucketName | b64enc | quote }}
  PUBLIC_IMAGE_URL: {{ .Values.secrets.publicImageUrl | b64enc | quote }}
  REDIS_HOST: {{ .Values.redis.host | b64enc | quote }}
  REDIS_PORT: {{ .Values.redis.port | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  JWT_REFRESH_TOKEN_KEY: {{ .Values.secrets.jwtRefreshTokenKey | b64enc | quote }}
  service-account.json: {{ .Values.secrets.serviceAccountJson | b64enc | quote }}