apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-car-rental
    app.kubernetes.io/managed-by: Helm
  name: nestjs-car-rental
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nestjs-car-rental
  type: NodePort
status:
  loadBalancer: {}
