apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs-car-rental.fullname" . }}-service
  labels:
    {{- include "nestjs-car-rental.labels" . | nindent 4 }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name | quote }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nestjs-car-rental.selectorLabels" . | nindent 4 }}