replicaCount: 3

nameOverride: "nestjs-car-rental"
fullnameOverride: "nestjs-car-rental"

image:
  repository: ravichandra1999/car-rental-backend
  pullPolicy: IfNotPresent
  tag: "2.0.0"

service:
  type: LoadBalancer
  port: 3000

redis:
  host: "nestjs-car-rental-redis-master"
  port: "6379"
  auth:
    enabled: false

secrets:
  databaseUrl: ""
  jwtSecretKey: ""
  jwtRefreshTokenKey: ""
  serviceAccountKeyPath: "/usr/src/app/service-account.json"
  storageBucketName: ""
  publicImageUrl: ""
  serviceAccountJson: ""